config/routes.rb
Rails.application.routes.draw do


  get 'summaries/index'

  devise_for :users
  resources :users, only: [:update, :show, :index]
  resources :questions do
    put :complete
  end

  resources :summaries

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
 
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up_vote' => 'votes#up_vote', as: :up_vote
    post '/down_vote' => 'votes#down_vote', as: :down_vote
  end
 



  get 'about' => 'welcome#about'

  get 'welcome/contact'

  resources :advertisements

  root to: 'welcome#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params.require(:question).permit(:title, :body, :resolved))
    if @question.save
      flash[:notice] = "Post was saved."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params.require(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "There was an error updating the question. Please try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      redirect_to @question, notice: "Question was destroyed"
    else
      flash[:error] = "There was an error deleting the question. Please try again."
      render :show
    end
  end

  def complete
    @question = Question.find(params[:question_id])
    @question.resolved = true
    @question.save
    redirect_to @question, notice: "Question was answered"
  end




end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: "form-control", placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 8, class: "form-control", placeholder: "Enter question body" %>
      </div>
      <div class="form-group">
        <%= q.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @questions.each do |q| %>
  <div class="media", "media-body">
    <h4 class="media-heading">
      <%= link_to q.title, q %>
    </h4>
  </div>
<% end %>
<p><p>
    <%= link_to "New", new_question_path, class: "btn btn-success" %>
</p></p>

app/views/questions/new.html.erb
<h1>New Question</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @question do |q| %>
      <div class="form-group">
        <%= q.label :title %>
        <%= q.text_field :title, class: "form-control", placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= q.label :body %>
        <%= q.text_area :body, rows: 8, class: "form-control", placeholder: "Enter question body" %>
      </div>
      <div class="form-group">
        <%= q.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %><small><%= "Resolved" if @question.resolved %></small></h1>

<p><%= @question.body %></p>
<p>
  <%= link_to "Resolved?", question_complete_path(@question), method: :put, class: "btn btn-success" %>
</p>
<p>
  <div class="btn-group">
    <%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>
    <%= link_to "Delete", @question, method: :delete, class: "btn btn-danger" %>
  </div>
</p>